rvm:
  - 2.1.1

bundler_args: --without development

language: node_js

node_js:
  - 0.10

notifications:
  email:
    on_success: change
    on_failure: always

before_install:
  - npm config set always-auth true
  - npm config set strict-ssl false
  - npm config set registry https://volusion.registry.nodejitsu.com
  - npm install -g grunt-cli bower
